# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161130_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
    ]
